modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
#issueTrackerURL="https://github.com/davidmaamoaix/JustAnotherAutoClicker/issues"
[[mods]]
modId="justanotherautoclicker"
version="1.0.0"
displayName="Just Another Auto Clicker"

credits="Thanks to hours of clicking in modded skyblock -.-"
authors="davidmaamoaix" #optional
description='''
A client-side auto clicker that reduces the grind of playing modded Minecraft.
'''