name: Build Minecraft Mod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '8'
    - run: chmod +x gradlew
    - run: ./gradlew clean build --no-daemon
    - uses: actions/upload-artifact@v4
      with:
        name: JustAnotherAutoClicker
        path: build/libs/*.jar
